# Generated by Django 3.2 on 2021-05-02 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exiting_value', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
